services:
  sdk-test:
    build:
      context: ./sdk-test
      dockerfile: Dockerfile
    environment:
      FLOCI_ENDPOINT: http://floci:4566
    depends_on:
      - floci
    profiles:
      - test

  sdk-test-node:
    build:
      context: ./sdk-test-node
      dockerfile: Dockerfile
    environment:
      FLOCI_ENDPOINT: http://floci:4566
    depends_on:
      - floci
    profiles:
      - test

  compat-cdk:
    build:
      context: ./compat-cdk
      dockerfile: Dockerfile
    environment:
      FLOCI_ENDPOINT: http://floci:4566
    depends_on:
      - floci
    profiles:
      - test

  compat-opentofu:
    build:
      context: ./compat-opentofu
      dockerfile: Dockerfile
    environment:
      FLOCI_ENDPOINT: http://floci:4566
    depends_on:
      - floci
    profiles:
      - test

  sdk-test-go:
    build:
      context: ./sdk-test-go
      dockerfile: Dockerfile
    environment:
      FLOCI_ENDPOINT: http://floci:4566
    depends_on:
      - floci
    profiles:
      - test

  sdk-test-python:
    build:
      context: ./sdk-test-python
      dockerfile: Dockerfile
    environment:
      FLOCI_ENDPOINT: http://floci:4566
    depends_on:
      - floci
    profiles:
      - test

  floci:
    build:
      context: .
      dockerfile: Dockerfile
#    image: hectorvent/floci
#    container_name: aws-local-native
    ports:
      - "4566:4566"
      - "6379-6399:6379-6399"
      - "7001-7099:7001-7099"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - ./data:/app/data
    environment:
      FLOCI_SERVICES_DOCKER_NETWORK: aws-local_default
      FLOCI_SERVICES_RDS_PROXY_BASE_PORT: "7001"
#      FLOCI_STORAGE_PERSISTENT_PATH: /app/data
#    profiles:env
#      - native
    networks:
      default:
        aliases:
          - localhost.localstack.cloud


