FROM eclipse-temurin:25-jre-alpine

ARG VERSION=latest
ARG INSTALL_AWS_CLI=false

ENV FLOCI_VERSION=${VERSION}

WORKDIR /app

RUN mkdir -p /app/data \
    && chown 1001:root /app \
    && chmod "g+rwX" /app \
    && chown 1001:root /app/data \
    && if [ "$INSTALL_AWS_CLI" = "true" ]; then \
             apk add --no-cache aws-cli; \
       fi

VOLUME /app/data

COPY --chown=1001:root target/quarkus-app quarkus-app/

EXPOSE 4566 6379-6399

HEALTHCHECK --interval=5s --timeout=3s --retries=5 \
    CMD wget -q --spider http://localhost:4566/_floci/health || exit 1

USER 1001

ENTRYPOINT ["java", "-jar", "quarkus-app/quarkus-run.jar", "-Dquarkus.http.host=0.0.0.0"]
